# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
literary = Genre.create({genre:"Literary"})
speculative = Genre.create({genre:"Speculative"})
romance = Genre.create({genre:"Romance"})

stories = Story.create([{title:"The Bet", author:"Anton Chekhov", genre_id:literary.id, snippet:"It was a dark autumn night. The old banker was walking up and down his study and remembering how, fifteen years before, he had given a party one autumn evening. There had been many clever men there, and there had been interesting conversations. Among other things they had talked of capital punishment. The majority of the guests, among whom were many journalists and intellectual men, disapproved of the death penalty. They considered that form of punishment out of date, immoral, and unsuitable for Christian States. In the opinion of some of them the death penalty ought to be replaced everywhere by imprisonment for life.
\“I don’t agree with you,\” said their host the banker. \“I have not tried either the death penalty or imprisonment for life, but if one may judge a priori, the death penalty is more moral and more humane than imprisonment for life. Capital punishment kills a man at once, but lifelong imprisonment kills him slowly. Which executioner is the more humane, he who kills you in a few minutes or he who drags the life out of you in the course of many years?\”
\“Both are equally immoral,\” observed one of the guests, \“for they both have the same object—to take away life. The State is not God. It has not the right to take away what it cannot restore when it wants to.\”
Among the guests was a young lawyer, a young man of five-and-twenty.", content:"It was a dark autumn night. The old banker was walking up and down his study and remembering how, fifteen years before, he had given a party one autumn evening. There had been many clever men there, and there had been interesting conversations. Among other things they had talked of capital punishment. The majority of the guests, among whom were many journalists and intellectual men, disapproved of the death penalty. They considered that form of punishment out of date, immoral, and unsuitable for Christian States. In the opinion of some of them the death penalty ought to be replaced everywhere by imprisonment for life.
\“I don’t agree with you,\” said their host the banker. \“I have not tried either the death penalty or imprisonment for life, but if one may judge a priori, the death penalty is more moral and more humane than imprisonment for life. Capital punishment kills a man at once, but lifelong imprisonment kills him slowly. Which executioner is the more humane, he who kills you in a few minutes or he who drags the life out of you in the course of many years?\”
\“Both are equally immoral,\” observed one of the guests, \“for they both have the same object—to take away life. The State is not God. It has not the right to take away what it cannot restore when it wants to.\”
Among the guests was a young lawyer, a young man of five-and-twenty. When he was asked his opinion, he said:
\“The death sentence and the life sentence are equally immoral, but if I had to choose between the death penalty and imprisonment for life, I would certainly choose the second. To live anyhow is better than not at all.\”
A lively discussion arose. The banker, who was younger and more nervous in those days, was suddenly carried away by excitement; he struck the table with his fist and shouted at the young man:
\“It’s not true! I’ll bet you two millions you wouldn’t stay in solitary confinement for five years.\”
\“If you mean that in earnest,\” said the young man, \“I’ll take the bet, but I would stay not five but fifteen years.\”
\“Fifteen? Done!\” cried the banker. \“Gentlemen, I stake two millions!\”
\“Agreed! You stake your millions and I stake my freedom!\” said the young man.
And this wild, senseless bet was carried out! The banker, spoilt and frivolous, with millions beyond his reckoning, was delighted at the bet. At supper he made fun of the young man, and said:
\“Think better of it, young man, while there is still time. To me two millions are a trifle, but you are losing three or four of the best years of your life. I say three or four, because you won’t stay longer. Don’t forget either, you unhappy man, that voluntary confinement is a great deal harder to bear than compulsory. The thought that you have the right to step out in liberty at any moment will poison your whole existence in prison. I am sorry for you.\”
And now the banker, walking to and fro, remembered all this, and asked himself: \“What was the object of that bet? What is the good of that man’s losing fifteen years of his life and my throwing away two millions? Can it prove that the death penalty is better or worse than imprisonment for life? No, no. It was all nonsensical and meaningless. On my part it was the caprice of a pampered man, and on his part simple greed for money....\”
Then he remembered what followed that evening. It was decided that the young man should spend the years of his captivity under the strictest supervision in one of the lodges in the banker’s garden. It was agreed that for fifteen years he should not be free to cross the threshold of the lodge, to see human beings, to hear the human voice, or to receive letters and newspapers. He was allowed to have a musical instrument and books, and was allowed to write letters, to drink wine, and to smoke. By the terms of the agreement, the only relations he could have with the outer world were by a little window made purposely for that object. He might have anything he wanted—books, music, wine, and so on—in any quantity he desired by writing an order, but could only receive them through the window. The agreement provided for every detail and every trifle that would make his imprisonment strictly solitary, and bound the young man to stay there exactly fifteen years, beginning from twelve o’clock of November 14, 1870, and ending at twelve o’clock of November 14, 1885. The slightest attempt on his part to break the conditions, if only two minutes before the end, released the banker from the obligation to pay him two millions.
For the first year of his confinement, as far as one could judge from his brief notes, the prisoner suffered severely from loneliness and depression. The sounds of the piano could be heard continually day and night from his lodge. He refused wine and tobacco. Wine, he wrote, excites the desires, and desires are the worst foes of the prisoner; and besides, nothing could be more dreary than drinking good wine and seeing no one. And tobacco spoilt the air of his room. In the first year the books he sent for were principally of a light character; novels with a complicated love plot, sensational and fantastic stories, and so on.
In the second year the piano was silent in the lodge, and the prisoner asked only for the classics. In the fifth year music was audible again, and the prisoner asked for wine. Those who watched him through the window said that all that year he spent doing nothing but eating and drinking and lying on his bed, frequently yawning and angrily talking to himself. He did not read books. Sometimes at night he would sit down to write; he would spend hours writing, and in the morning tear up all that he had written. More than once he could be heard crying.
In the second half of the sixth year the prisoner began zealously studying languages, philosophy, and history. He threw himself eagerly into these studies—so much so that the banker had enough to do to get him the books he ordered. In the course of four years some six hundred volumes were procured at his request. It was during this period that the banker received the following letter from his prisoner:
\“My dear Jailer, I write you these lines in six languages. Show them to people who know the languages. Let them read them. If they find not one mistake I implore you to fire a shot in the garden. That shot will show me that my efforts have not been thrown away. The geniuses of all ages and of all lands speak different languages, but the same flame burns in them all. Oh, if you only knew what unearthly happiness my soul feels now from being able to understand them!\” The prisoner’s desire was fulfilled. The banker ordered two shots to be fired in the garden.
Then after the tenth year, the prisoner sat immovably at the table and read nothing but the Gospel. It seemed strange to the banker that a man who in four years had mastered six hundred learned volumes should waste nearly a year over one thin book easy of comprehension. Theology and histories of religion followed the Gospels.
In the last two years of his confinement the prisoner read an immense quantity of books quite indiscriminately. At one time he was busy with the natural sciences, then he would ask for Byron or Shakespeare. There were notes in which he demanded at the same time books on chemistry, and a manual of medicine, and a novel, and some treatise on philosophy or theology. His reading suggested a man swimming in the sea among the wreckage of his ship, and trying to save his life by greedily clutching first at one spar and then at another.

II
The old banker remembered all this, and thought:
\“To-morrow at twelve o’clock he will regain his freedom. By our agreement I ought to pay him two millions. If I do pay him, it is all over with me: I shall be utterly ruined.\”
Fifteen years before, his millions had been beyond his reckoning; now he was afraid to ask himself which were greater, his debts or his assets. Desperate gambling on the Stock Exchange, wild speculation and the excitability which he could not get over even in advancing years, had by degrees led to the decline of his fortune and the proud, fearless, self-confident millionaire had become a banker of middling rank, trembling at every rise and fall in his investments. \“Cursed bet!\” muttered the old man, clutching his head in despair. \“Why didn’t the man die? He is only forty now. He will take my last penny from me, he will marry, will enjoy life, will gamble on the Exchange; while I shall look at him with envy like a beggar, and hear from him every day the same sentence: ‘I am indebted to you for the happiness of my life, let me help you!’ No, it is too much! The one means of being saved from bankruptcy and disgrace is the death of that man!\”
It struck three o’clock, the banker listened; everyone was asleep in the house and nothing could be heard outside but the rustling of the chilled trees. Trying to make no noise, he took from a fireproof safe the key of the door which had not been opened for fifteen years, put on his overcoat, and went out of the house.
It was dark and cold in the garden. Rain was falling. A damp cutting wind was racing about the garden, howling and giving the trees no rest. The banker strained his eyes, but could see neither the earth nor the white statues, nor the lodge, nor the trees. Going to the spot where the lodge stood, he twice called the watchman. No answer followed. Evidently the watchman had sought shelter from the weather, and was now asleep somewhere either in the kitchen or in the greenhouse.
\“If I had the pluck to carry out my intention,\” thought the old man, \“suspicion would fall first upon the watchman.\”
He felt in the darkness for the steps and the door, and went into the entry of the lodge. Then he groped his way into a little passage and lighted a match. There was not a soul there. There was a bedstead with no bedding on it, and in the corner there was a dark cast-iron stove. The seals on the door leading to the prisoner’s rooms were intact.
When the match went out the old man, trembling with emotion, peeped through the little window. A candle was burning dimly in the prisoner’s room. He was sitting at the table. Nothing could be seen but his back, the hair on his head, and his hands. Open books were lying on the table, on the two easy-chairs, and on the carpet near the table.
Five minutes passed and the prisoner did not once stir. Fifteen years’ imprisonment had taught him to sit still. The banker tapped at the window with his finger, and the prisoner made no movement whatever in response. Then the banker cautiously broke the seals off the door and put the key in the keyhole. The rusty lock gave a grating sound and the door creaked. The banker expected to hear at once footsteps and a cry of astonishment, but three minutes passed and it was as quiet as ever in the room. He made up his mind to go in.
At the table a man unlike ordinary people was sitting motionless. He was a skeleton with the skin drawn tight over his bones, with long curls like a woman’s and a shaggy beard. His face was yellow with an earthy tint in it, his cheeks were hollow, his back long and narrow, and the hand on which his shaggy head was propped was so thin and delicate that it was dreadful to look at it. His hair was already streaked with silver, and seeing his emaciated, aged-looking face, no one would have believed that he was only forty. He was asleep.... In front of his bowed head there lay on the table a sheet of paper on which there was something written in fine handwriting.
\“Poor creature!\” thought the banker, \“he is asleep and most likely dreaming of the millions. And I have only to take this half-dead man, throw him on the bed, stifle him a little with the pillow, and the most conscientious expert would find no sign of a violent death. But let us first read what he has written here....\”
The banker took the page from the table and read as follows:
\“To-morrow at twelve o’clock I regain my freedom and the right to associate with other men, but before I leave this room and see the sunshine, I think it necessary to say a few words to you. With a clear conscience I tell you, as before God, who beholds me, that I despise freedom and life and health, and all that in your books is called the good things of the world.
\“For fifteen years I have been intently studying earthly life. It is true I have not seen the earth nor men, but in your books I have drunk fragrant wine, I have sung songs, I have hunted stags and wild boars in the forests, have loved women.... Beauties as ethereal as clouds, created by the magic of your poets and geniuses, have visited me at night, and have whispered in my ears wonderful tales that have set my brain in a whirl. In your books I have climbed to the peaks of Elburz and Mont Blanc, and from there I have seen the sun rise and have watched it at evening flood the sky, the ocean, and the mountain-tops with gold and crimson. I have watched from there the lightning flashing over my head and cleaving the storm-clouds. I have seen green forests, fields, rivers, lakes, towns. I have heard the singing of the sirens, and the strains of the shepherds’ pipes; I have touched the wings of comely devils who flew down to converse with me of God.... In your books I have flung myself into the bottomless pit, performed miracles, slain, burned towns, preached new religions, conquered whole kingdoms....
\“Your books have given me wisdom. All that the unresting thought of man has created in the ages is compressed into a small compass in my brain. I know that I am wiser than all of you.
\“And I despise your books, I despise wisdom and the blessings of this world. It is all worthless, fleeting, illusory, and deceptive, like a mirage. You may be proud, wise, and fine, but death will wipe you off the face of the earth as though you were no more than mice burrowing under the floor, and your posterity, your history, your immortal geniuses will burn or freeze together with the earthly globe.
\“You have lost your reason and taken the wrong path. You have taken lies for truth, and hideousness for beauty. You would marvel if, owing to strange events of some sorts, frogs and lizards suddenly grew on apple and orange trees instead of fruit, or if roses began to smell like a sweating horse; so I marvel at you who exchange heaven for earth. I don’t want to understand you.
\“To prove to you in action how I despise all that you live by, I renounce the two millions of which I once dreamed as of paradise and which now I despise. To deprive myself of the right to the money I shall go out from here five hours before the time fixed, and so break the compact....\”
When the banker had read this he laid the page on the table, kissed the strange man on the head, and went out of the lodge, weeping. At no other time, even when he had lost heavily on the Stock Exchange, had he felt so great a contempt for himself. When he got home he lay on his bed, but his tears and emotion kept him for hours from sleeping.
Next morning the watchmen ran in with pale faces, and told him they had seen the man who lived in the lodge climb out of the window into the garden, go to the gate, and disappear. The banker went at once with the servants to the lodge and made sure of the flight of his prisoner. To avoid arousing unnecessary talk, he took from the table the writing in which the millions were renounced, and when he got home locked it up in the fireproof safe.
"}, {title:"Eveline", author:"James Joyce", genre_id:romance.id, content: "She sat at the window watching the evening invade the avenue. Her head was leaned against the window curtains and in her nostrils was the odour of dusty cretonne. She was tired.

Few people passed. The man out of the last house passed on his way home; she heard his footsteps clacking along the concrete pavement and afterwards crunching on the cinder path before the new red houses. One time there used to be a field there in which they used to play every evening with other people’s children. Then a man from Belfast bought the field and built houses in it—not like their little brown houses but bright brick houses with shining roofs. The children of the avenue used to play together in that field—the Devines, the Waters, the Dunns, little Keogh the cripple, she and her brothers and sisters. Ernest, however, never played: he was too grown up. Her father used often to hunt them in out of the field with his blackthorn stick; but usually little Keogh used to keep nix and call out when he saw her father coming. Still they seemed to have been rather happy then. Her father was not so bad then; and besides, her mother was alive. That was a long time ago; she and her brothers and sisters were all grown up; her mother was dead. Tizzie Dunn was dead, too, and the Waters had gone back to England. Everything changes. Now she was going to go away like the others, to leave her home.

Home! She looked round the room, reviewing all its familiar objects which she had dusted once a week for so many years, wondering where on earth all the dust came from. Perhaps she would never see again those familiar objects from which she had never dreamed of being divided. And yet during all those years she had never found out the name of the priest whose yellowing photograph hung on the wall above the broken harmonium beside the coloured print of the promises made to Blessed Margaret Mary Alacoque. He had been a school friend of her father. Whenever he showed the photograph to a visitor her father used to pass it with a casual word:

\“He is in Melbourne now.\”

She had consented to go away, to leave her home. Was that wise? She tried to weigh each side of the question. In her home anyway she had shelter and food; she had those whom she had known all her life about her. Of course she had to work hard, both in the house and at business. What would they say of her in the Stores when they found out that she had run away with a fellow? Say she was a fool, perhaps; and her place would be filled up by advertisement. Miss Gavan would be glad. She had always had an edge on her, especially whenever there were people listening.

\“Miss Hill, don’t you see these ladies are waiting?\”

\“Look lively, Miss Hill, please.\”

She would not cry many tears at leaving the Stores.

But in her new home, in a distant unknown country, it would not be like that. Then she would be married—she, Eveline. People would treat her with respect then. She would not be treated as her mother had been. Even now, though she was over nineteen, she sometimes felt herself in danger of her father’s violence. She knew it was that that had given her the palpitations. When they were growing up he had never gone for her like he used to go for Harry and Ernest, because she was a girl; but latterly he had begun to threaten her and say what he would do to her only for her dead mother’s sake. And now she had nobody to protect her. Ernest was dead and Harry, who was in the church decorating business, was nearly always down somewhere in the country. Besides, the invariable squabble for money on Saturday nights had begun to weary her unspeakably. She always gave her entire wages—seven shillings—and Harry always sent up what he could but the trouble was to get any money from her father. He said she used to squander the money, that she had no head, that he wasn’t going to give her his hard-earned money to throw about the streets, and much more, for he was usually fairly bad of a Saturday night. In the end he would give her the money and ask her had she any intention of buying Sunday’s dinner. Then she had to rush out as quickly as she could and do her marketing, holding her black leather purse tightly in her hand as she elbowed her way through the crowds and returning home late under her load of provisions. She had hard work to keep the house together and to see that the two young children who had been left to her charge went to school regularly and got their meals regularly. It was hard work—a hard life—but now that she was about to leave it she did not find it a wholly undesirable life.

She was about to explore another life with Frank. Frank was very kind, manly, open-hearted. She was to go away with him by the night-boat to be his wife and to live with him in Buenos Ayres where he had a home waiting for her. How well she remembered the first time she had seen him; he was lodging in a house on the main road where she used to visit. It seemed a few weeks ago. He was standing at the gate, his peaked cap pushed back on his head and his hair tumbled forward over a face of bronze. Then they had come to know each other. He used to meet her outside the Stores every evening and see her home. He took her to see The Bohemian Girl and she felt elated as she sat in an unaccustomed part of the theatre with him. He was awfully fond of music and sang a little. People knew that they were courting and, when he sang about the lass that loves a sailor, she always felt pleasantly confused. He used to call her Poppens out of fun. First of all it had been an excitement for her to have a fellow and then she had begun to like him. He had tales of distant countries. He had started as a deck boy at a pound a month on a ship of the Allan Line going out to Canada. He told her the names of the ships he had been on and the names of the different services. He had sailed through the Straits of Magellan and he told her stories of the terrible Patagonians. He had fallen on his feet in Buenos Ayres, he said, and had come over to the old country just for a holiday. Of course, her father had found out the affair and had forbidden her to have anything to say to him.

\“I know these sailor chaps,\” he said.

One day he had quarrelled with Frank and after that she had to meet her lover secretly.

The evening deepened in the avenue. The white of two letters in her lap grew indistinct. One was to Harry; the other was to her father. Ernest had been her favourite but she liked Harry too. Her father was becoming old lately, she noticed; he would miss her. Sometimes he could be very nice. Not long before, when she had been laid up for a day, he had read her out a ghost story and made toast for her at the fire. Another day, when their mother was alive, they had all gone for a picnic to the Hill of Howth. She remembered her father putting on her mother’s bonnet to make the children laugh.

Her time was running out but she continued to sit by the window, leaning her head against the window curtain, inhaling the odour of dusty cretonne. Down far in the avenue she could hear a street organ playing. She knew the air. Strange that it should come that very night to remind her of the promise to her mother, her promise to keep the home together as long as she could. She remembered the last night of her mother’s illness; she was again in the close dark room at the other side of the hall and outside she heard a melancholy air of Italy. The organ-player had been ordered to go away and given sixpence. She remembered her father strutting back into the sickroom saying:

\“Damned Italians! coming over here!\”

As she mused the pitiful vision of her mother’s life laid its spell on the very quick of her being—that life of commonplace sacrifices closing in final craziness. She trembled as she heard again her mother’s voice saying constantly with foolish insistence:

\“Derevaun Seraun! Derevaun Seraun!\”

She stood up in a sudden impulse of terror. Escape! She must escape! Frank would save her. He would give her life, perhaps love, too. But she wanted to live. Why should she be unhappy? She had a right to happiness. Frank would take her in his arms, fold her in his arms. He would save her.



She stood among the swaying crowd in the station at the North Wall. He held her hand and she knew that he was speaking to her, saying something about the passage over and over again. The station was full of soldiers with brown baggages. Through the wide doors of the sheds she caught a glimpse of the black mass of the boat, lying in beside the quay wall, with illumined portholes. She answered nothing. She felt her cheek pale and cold and, out of a maze of distress, she prayed to God to direct her, to show her what was her duty. The boat blew a long mournful whistle into the mist. If she went, tomorrow she would be on the sea with Frank, steaming towards Buenos Ayres. Their passage had been booked. Could she still draw back after all he had done for her? Her distress awoke a nausea in her body and she kept moving her lips in silent fervent prayer.

A bell clanged upon her heart. She felt him seize her hand:

\“Come!\”

All the seas of the world tumbled about her heart. He was drawing her into them: he would drown her. She gripped with both hands at the iron railing.

\“Come!\”

No! No! No! It was impossible. Her hands clutched the iron in frenzy. Amid the seas she sent a cry of anguish!

\“Eveline! Evvy!\”

He rushed beyond the barrier and called to her to follow. He was shouted at to go on but he still called to her. She set her white face to him, passive, like a helpless animal. Her eyes gave him no sign of love or farewell or recognition.", snippet:"She sat at the window watching the evening invade the avenue. Her head was leaned against the window curtains and in her nostrils was the odour of dusty cretonne. She was tired.

Few people passed. The man out of the last house passed on his way home; she heard his footsteps clacking along the concrete pavement and afterwards crunching on the cinder path before the new red houses. One time there used to be a field there in which they used to play every evening with other people’s children."}, {title:"Treks End", author:"John Walker", snippet:"I saw it happen. I witnessed the end of the world. And since I'm the only human who saw it, I'm going to write it down, even though there won't be any more generations of humans to read it. Somehow I need to. Perhaps another species will learn from our experience. Probably not. Certainly we never imagined how dangerous a galaxy we grew up in.", genre_id:speculative.id, content:"I saw it happen. I witnessed the end of the world. And since I'm the only human who saw it, I'm going to write it down, even though there won't be any more generations of humans to read it. Somehow I need to. Perhaps another species will learn from our experience. Probably not. Certainly we never imagined how dangerous a galaxy we grew up in.

Context: even though born decades after Cernan made the last bootprint on the Moon, I've dreamed of going into space for as long as I can remember. I'd lie in bed at night and imagine my bedroom suddenly transformed into zero G. I'd push myself off from a wall, feeling the exquisite back-pressure of pure inertia as I squeezed my fingers to launch myself; I'd do lazy back flips and twists in mid-air, then use my toes to spring from the opposite wall. I occupied myself with all the usual space-kid stuff: model rockets, reading astronaut memoirs, even joining one of the groups lobbying for more taxpayer money for socialist space programs. But even in high school I'd faced the fact that the only way I'd ever make it to orbit would be to turn myself into a politically-correct government funded parasite, then spend a career in a program completely decoupled from the true human destiny in space. No thanks; I'd rather program computers.

Then came the Fourth of August: decapitation. Amid the shock and chaos that ensued, only a few (far wiser than this high school kid) imagined that the destruction of Washington would indirectly open the road to the stars. Like so many of the private initiatives that sprang up in the years of recovery and the dawn of the Republic, the Band of Billionaires and the GEOSPACE corporation they founded would invigorate industries grown sclerotic from decades of regulation and inspire a generation to realise their dreams, working toward their own personal future beyond the home planet.

It sure was that way for me. In my junior year of college, I changed my major to aerospace, and started to catch up on thermogoddamics, fluids, and all the real engineering I'd ignored while fooling around with computers. It would take me an extra year to graduate, but equip me for a career in space.

After the obligatory master's degree, flight school indenture, National Service as a militia pilot, and five years of working up the ladder at GEOSPACE, I'd made it off-planet as an interorbital ferry pilot (the word \“shuttle\” having become as disreputable as \“appeasement\” and \“root cause\”), driving technicians and gear back and forth between the Low Earth Orbit logistics base and the GEOCans. After economics finally prevailed over national pride, it was obvious that sprinkling dozens of satellites around geosynchronous orbit was an insane way to go about global communication. Far wiser to concentrate everything in a small number of geostationary platforms (visionaries always fastened on the minimum of three, but actually six ultimately made the most sense), cross-linked by high bandwidth lasers. On each GEOCan (supposedly from \“GEOSPACE Communication Array Node\”, but really because the pressurised module resembled a beer can), tenants shared solar panels, transmitters and phased array antennas, but supplied their own switching, signal processing, and beam directing gear. The six GEOCans were hardly high tech, but then nothing GEOSPACE did was, really. But they made money—cubic acres of the stuff. The GEOCans were actually based on the design of the laboratory modules for the grotesque \“International Space Station\” that scattered debris all over China two years after the decapitation. Once the GEOSPACE engineers ripped out all the gold-plating and safetyland silliness, what remained was a suitable pressure vessel and logistics system for the GEOCans.

This was my third trip to a GEOCan as pilot—this time GEOCan Asia, above Singapore at 105 degrees East; what a view! We'd embarked three tonnes of cargo and five technicians at the GEOSPACE LEO base for the run uphill. Like most logistics missions, we'd top up station keeping fuel, but most of our cargo was changeouts for gear in the racks inside the GEOCan—signal processors, amplifiers, and so forth. The techs understand this stuff (or at least how to hook it up); I just drive the bus. After docking, completing the propellant transfer, hooking up the life support system in the GEOCan to the consumables and scrubbers in the ferry, and checking the atmosphere in the GEOCan, my work was done until it was time to undock and burn Earth transfer orbit. The techs were busy in the GEOCan removing old gear and installing the new, muttering to themselves in Russian, Chinese, Korean, Japanese, and English, and bitching to one another in the latter. I was floating in my ferry pilot's seat, listening to the chatter on the intercom, but mostly alternating between studying and looking out the window.

Studying—my next career goal (it seems so trivial, now) was to land a first officer's seat on a GEOSPACE Trans-Atmospheric Transport, then move up after a couple of years to captain. Flying back and forth from Omaha spaceport to low Earth orbit may not seem as romantic as boosting up to where the Earth looks the size of a soccer ball, but it pays a lot better, plus you get to sleep in your own bed every night and shower regularly. With the majority of TAT flights already going to the first GEOSPACE Orbital Hotel (dubbed \“Sin Star\” by the fundies—beats me what so disturbs them about zero-G volleyball), and the tourist sector growing rapidly as volume drove the costs down, that's where the money was. Besides, with luck and enough seniority in the left seat of a TAT, I'd be in line to command a lunar ferry once GEOSPACE started to open the Moon to tourism.

Now, GEOSPACE could possibly afford to lose a ferry with a bunch of techs and some comm gear. The insurance would cover it and, Hell, we all fought to get our jobs. But losing a TAT with 70 tourists returning from holiday would in all likelihood sink not only the space tourism business but GEOSPACE as well. To be entrusted with one of those vehicles you had to be the very best of the very best.

Which I was, of course. All I had to do was prove it.

So, there I was, reviewing the TAT systems manual for the thousandth time in preparation for my first \“informal\” interview with the chief of the TAT crew office next month. I can hand fly anything with better L/D than a watermelon, but there's only so much a meat computer can absorb in a given amount of time from prose like, \“If the primary yaw RCS fails and the prime FCS fails over to the backup yaw RCS and the RCS anomaly annunciator fails to indicate the fault, the master caution and warning system will indicate status 5104, which may be queried on the primary or backup flight display system. But if the backup FCS is active, no indication of the failure of primary yaw RCS will be given if the RCS anomaly annunciator has also failed.\” Imagine seventeen thousand pages of this, and eventually being tested on all of it in the simulator.

Mine eyes, having thoroughly glazed over, gazed upward from the screen toward the ever-fascinating Earth almost centred in the cockpit window. Suddenly, what is that? An impossibly brilliant star came into view from the right, moving toward the Earth with an angular velocity you simply never see in space. It may have been bigger than a point source, but I don't think so. It took no more than a second to cross the two Earth diameters from where I first spotted it to the point of impact not far from the illuminated limb, a bit north of the equator.

All Hell broke loose. The impact instantaneously ejected a plume of plasma, which began to rise outward at a speed much slower than the impactor arrived. I'm not sure about my perception of time from here on. There was no camera to record it, and when you're seeing something you've never, ever, expected to see, time gets elastic. I remember my parents talking about feeling that way when \“the twin towers fell.\” I'm too young to remember that.

Whatever the timing, this is what happened. The Earth seemed to shudder, then the ocean began to blow off into a steam cloud which visibly inflated the atmosphere and turned it white as it progressed along a spherical front from the point of impact. Then the Earth, which now seemed puckered near the impact point on the right limb where the plasma was dispersing into space, belched out a spout of incandescent magma from behind the dark left limb. The spout may have gone into orbit; there may be a new Moon. Too bad there won't be any lovers to see it. The white wave continued to spread around the globe as the shock wave progressed and the oceans vaporised. It moved slower than one might expect, but advanced at an absolutely constant rate: the curtain of extinction ringing down upon the biosphere. Then a shudder happened about 270 degrees from the point of impact and a white band began to propagate outward in both directions from there. When all of these converged behind the dark limb something happened which looked like a secondary ejecta event, but I'm not sure about that.

Moments after the impact I keyed the intercom to the techs in the GEOCan. \“Folks, something's happened. Get up here right away.\” I wasn't trying to demonstrate sang-froid—I'm a pilot with more than 3000 hours and that's how I talk. One by one, they floated onto the flight deck and looked out the window. All of us were struck silent by what we were witnessing. We'd lost the feeds from everything on Earth within 20 seconds of the impact. The cross-feeds from the other GEOCans were still up but nothing but carrier. By the time anybody spoke, Earth was a featureless white ball with ejecta coalescing into an arc around it.

I described the arrival of the impactor and the events before they'd arrived on the flight deck. Vasily shook his head and said, \“We've known this risk since Tunguska, and what have we done—nothing. We go to space so monkeys can chatter at one another.\” Yutaka disagreed, \“This was not an impact by a solar system body.\” He turned to me. \“Peter, how long did you say it took for the impactor to come in from the point where you spotted it?\” \“About a second to cross two Earth diameters\”, I replied.

Yutaka drew his computer from its holster and tapped away for a few seconds. He paused, shook his head, tapped some more, then said slowly, \“Whatever it was, it came in at about ten percent of the speed of light. Dynamically, that object didn't belong to the solar system, or for that matter the galaxy. It was going…\”, tap, tap, tap, \“more than seven hundred times too fast to be gravitationally bound to the Sun, and sixty times the escape velocity of the galaxy.\”

\“So what was it?\”, asked Jiang. I pondered the question. \“Well, there are really only two possibilities\”, I said. \“An impactor's first acquiring relativistic velocity by successive random gravitational encounters, then managing to hit a target the size of the Earth is something so fantastically improbable it's unlikely to have happened anywhere in the universe since the big bang. So if that's what happened, we have just witnessed the single worst case of bad luck since Creation.\” \“Other possibility?\”, asked Vasily.

\“That we've just witnessed the deliberate destruction of the Earth by hostile aliens.\”

We talked about these issues for several hours and then, having nothing more to say and nothing to look at besides the white ball our home planet had become, one by one we went to sleep. Maybe you find it hard to imagine going to sleep after watching the destruction of your entire species, but eventually you get tired enough and sleep overtakes you. It's not like we expected a wake-up call next morning.

The next day we monitored and tried calling on all frequencies the GEOCan could access. The GPS constellation remained on the air, but the ephemeris in the satellites showed no update since the impact. The other GEOCans maintained their laser links with ours, but all indicated no uplink from Earth or LEO and our transmissions relayed through them elicited no reply. We were the only crew above LEO at the time of the impact. The clearly visible expansion of the atmosphere as the oceans flashed into steam had been more than enough to bring down any satellite in LEO, including the logistics base, Hotel, and any TATs en route. We had supplies for 12 days at GEO even though we'd only expected to stay for three. With nothing better to do, we spent most of the day in rather maudlin recollections of Earth. Our crew, all young, male, and apart from Jiang, single, probably took the end of human history better than most might have, but there'd be no way to repeat the experiment with other humans. We were it.

Three days passed. We did routine housekeeping, scanned Earth and the other GEOCans for signals, finding nothing. We took pictures of the coalescence of the ejecta from the impact into a ring which now seemed to be punctuated by the core of an inner moon. There was nothing else to do. All of us were mission-oriented people, so we did our jobs. It seems crazy, but what was the alternative? I mean, otherwise, we might be fired.

Around mid-day, four days after the impact, the ship arrived.

Yutaka, Jiang, and I were on the flight deck when it appeared like a streak of light and seemed to instantaneously stop twenty metres in front of the ferry. It was huge, about 100 metres in diameter, perfectly spherical. The surface was primarily white, but with sub-structure that appeared fractal and seemed to constantly change. A tube extended from the craft toward our front docking port, where it engaged the drogue and triggered the contingency rescue hard dock. Over the intercom we heard, \“Please open the hatch; we need to talk to you.\” This in midwestern American English.

When I cracked the hatch, there was no residual pressure differential, but the smell could knock you down. They floated through the hatch, one after another, five in all. If you're big on diversity, these are your kind of aliens. Two almost resembled greys out of a Whitley Streiber nightmare—dinky, big almond-shaped black eyes, gracile limbs, egg-shaped heads…but leathery ears, like a fox bat. Two more were vaguely lizard-like, but not all that creepy. They stood erect on two stumpy legs and had no obvious tail. Then there was the one with the tentacles on his (her, its?) face which smelled like…well, I've never smelled anything like that before…brrrr. They all seemed to have no difficulty breathing our atmosphere and if we smelled as bad to them, they gave no sign of it.

They seemed to have a strong sense of hierarchy. After speaking briefly to each member of the crew, each in his own mother tongue (colloquially, and without obvious accent), one of the greys approached and addressed me as \“captain\”. I denied the rank, but the grey insisted, \“Based on our study of your species, one speaks for all on your ships.\” With assent from the techs, I accepted that responsibility.

In bad situations, I like to get out in front of things, and this was about as bad a situation as I could imagine. I put my hands on my hips and asked the grey who stood before me, \“Was it you who destroyed our world?\”

\“It was.\”

\“Why?\”

The grey replied, \“Because your planet presented an unprecedented risk to peace in the galaxy.\”

I paused, held my breath for a few seconds, then said, as calmly as I could manage, \“Unprecedented risk? You have interstellar travel; you destroy entire planets with relativistic bullets, and you have no apparent compunctions about planetary ecocide. And you call us a risk?\”

The grey raised its head and fixed me with its huge black eyes. They're not hypnotic—just black—nothing there at all, not even a reflection. It said, \“We monitor electromagnetic emissions of all planets crossing the technological threshold. Never before have we found one which represents such a grave peril. Your species posed a threat so immediate, so acute, that not to act would have been negligent. We are not aggressors; we are galactic peacekeepers. We do not interfere with the development of any civilisation unless it threatens all of us who have renounced warfare.

\“Your United Federation of Planets, with its incessant conflict and meddling with other developing civilisations in direct violation of its own Prime Directive and our Fundamental Charter presented a clear and present danger to us. With warp drive, which we do not possess, and cloaking and subspace communications which enabled your Federation vessels and facilities to elude our sensors, we had no alternative but to act preemptively and decisively in self defence. We could not risk a conflict with your Federation.\”

Vasily was the most enthusiastic Trekker on board. He flashed crimson, then shouted,

\“But there is no Federation, no warp, no cloaking, no subspace. That's nothing but science fiction.\”

The aliens looked at one other and exchanged some words in a language none of us understood. Then the grey turned back to me and spoke.

\“We know science. What is fiction?\”"}])
